package com.loganalyzer.parsing.service;

import com.loganalyzer.parsing.model.entity.ParsedLog;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class AlertService {

    @Autowired
    private JavaMailSender mailSender;

    @Value("${app.alert.recipient-email}")
    private String recipient;

    @Async // Yeh mail ko background mein bhejega
    public void sendCriticalAlert(ParsedLog logDetails) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setTo(recipient);
            helper.setSubject("🚨 CRITICAL: AI Log Analysis Report - " + logDetails.getServiceName());

            // Professional HTML Template
            String htmlContent = String.format("""
                <div style="font-family: Arial, sans-serif; border: 1px solid #ddd; border-radius: 8px; padding: 20px; max-width: 600px;">
                    <h2 style="color: #d9534f;">Critical Incident Detected</h2>
                    <p><strong>Service:</strong> %s</p>
                    <p><strong>Time:</strong> %s</p>
                    <hr style="border: 0; border-top: 1px solid #eee;" />
                    
                    <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px;">
                        <h3 style="margin-top: 0; color: #333;">Raw Error</h3>
                        <code style="display: block; word-break: break-all; color: #c7254e;">%s</code>
                    </div>

                    <div style="margin-top: 20px;">
                        <h3 style="color: #5bc0de;">AI Root Cause Analysis</h3>
                        <p style="line-height: 1.6;">%s</p>
                    </div>

                    <div style="margin-top: 20px; padding: 10px; background-color: #dff0d8; border-radius: 5px;">
                        <h3 style="color: #3c763d; margin-top: 0;">Recommended Fixing Steps</h3>
                        <p>%s</p>
                    </div>
                    
                    <p style="font-size: 12px; color: #777; margin-top: 30px;">
                        This is an automated alert generated by your AI Log Analyzer.
                    </p>
                </div>
                """, 
                logDetails.getServiceName(), 
                logDetails.getTimestamp(),
                logDetails.getRawMessage(),
                logDetails.getAiRootCause() != null ? logDetails.getAiRootCause() : "Analysis failed or pending.",
                logDetails.getAiFixingSteps() != null ? logDetails.getAiFixingSteps() : "Manual investigation required."
            );

            helper.setText(htmlContent, true); // True means it's HTML
            mailSender.send(message);
            log.info("✅ SUCCESS: HTML Professional Alert sent successfully to {}", recipient);

        } catch (Exception e) {
            log.error("❌ SMTP ERROR: Failed to send HTML email. Reason: {}", e.getMessage());
        }
    }
}