package com.loganalyzer.ai.model;

import lombok.Data;
import java.util.List;

@Data
public class BedrockResponse {
    private String id;
    private String type;
    private String role;
    private List<Content> content;
    private String stop_reason;

    @Data
    public static class Content {
        private String type;
        private String text; // Yahi humara actual AI analysis result hai
    }

    /**
     * Helper method to quickly extract the first response text
     */
    public String getFirstText() {
        if (content != null && !content.isEmpty()) {
            return content.get(0).getText();
        }
        return "No analysis generated by AI.";
    }
}