server:
  port: 8082

spring:
  application:
    name: log-parsing-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ay2484900@gmail.com
    password: "meyp dyuk ebdq sbzl"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  main:
    allow-bean-definition-overriding: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: parsing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  elasticsearch:
    uris: http://localhost:9200

# AWS Configuration (Corrected Indentation)
aws:
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET_KEY:}
  region: "ap-south-1"
  bedrock:
    model-id: "anthropic.claude-3-haiku-20240307-v1:0"

app:
  alert:
    recipient-email: ay2484900@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.loganalyzer.parsing: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.elasticsearch: INFO