server:
  port: 8082

spring:
  application:
    name: log-parsing-service
  
  elasticsearch:
    uris: http://localhost:9200
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-parsing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.loganalyzer: DEBUG
