server:
  port: 8081

spring:
  application:
    name: log-ingestion-service
  
  data:
    mongodb:
      uri: mongodb+srv://ay2484900:RDGn4i1DP0kI6R6B@mernyard.qgzpk.mongodb.net/log_analyzer?retryWrites=true&w=majority
      database: log_analyzer
    
    elasticsearch:
      uris: http://localhost:9200


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.loganalyzer: DEBUG
    org.springframework.kafka: INFO
